/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum Icon {
    CHECK = 0,
    EXCLAMATION_CIRCLE = 1,
    BAN = 2,
    SMAILE = 3
}
