/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
import * as PdpRequest from "./PdpRequest";
import * as PdpResponse from "./PdpResponse";
export const serviceName: string = "Market";
export const annotations: thrift.IThriftAnnotations = {};
export const methodAnnotations: thrift.IMethodAnnotations = {
    getPdp: {
        annotations: {
            rest_verb: "get",
            rest_path: "/new_endpoint/{productId}"
        },
        fieldAnnotations: {}
    }
};
export const methodNames: Array<string> = ["getPdp"];
export const methodParameters: {
    [methodName: string]: number;
} = {
    getPdp: 2
};
export interface IGetPdp__Args {
    request: PdpRequest.IPdpRequest;
}
export interface IGetPdp__ArgsArgs {
    request: PdpRequest.IPdpRequestArgs;
}
export const GetPdp__ArgsCodec: thrift.IStructCodec<IGetPdp__ArgsArgs, IGetPdp__Args> = {
    encode(args: IGetPdp__ArgsArgs, output: thrift.TProtocol): void {
        const obj: any = {
            request: args.request
        };
        output.writeStructBegin("GetPdp__Args");
        if (obj.request != null) {
            output.writeFieldBegin("request", thrift.TType.STRUCT, 1);
            PdpRequest.PdpRequestCodec.encode(obj.request, output);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[request] is unset!");
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IGetPdp__Args {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_1: PdpRequest.IPdpRequest = PdpRequest.PdpRequestCodec.decode(input);
                        _args.request = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.request !== undefined) {
            return {
                request: _args.request
            };
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read GetPdp__Args from input");
        }
    }
};
export class GetPdp__Args extends thrift.StructLike implements IGetPdp__Args {
    public request: PdpRequest.IPdpRequest;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IGetPdp__ArgsArgs) {
        super();
        if (args.request != null) {
            const value_2: PdpRequest.IPdpRequest = new PdpRequest.PdpRequest(args.request);
            this.request = value_2;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[request] is unset!");
        }
    }
    public static read(input: thrift.TProtocol): GetPdp__Args {
        return new GetPdp__Args(GetPdp__ArgsCodec.decode(input));
    }
    public static write(args: IGetPdp__ArgsArgs, output: thrift.TProtocol): void {
        return GetPdp__ArgsCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return GetPdp__ArgsCodec.encode(this, output);
    }
}
export interface IGetPdp__Result {
    success?: PdpResponse.IPdpResponse;
}
export interface IGetPdp__ResultArgs {
    success?: PdpResponse.IPdpResponseArgs;
}
export const GetPdp__ResultCodec: thrift.IStructCodec<IGetPdp__ResultArgs, IGetPdp__Result> = {
    encode(args: IGetPdp__ResultArgs, output: thrift.TProtocol): void {
        const obj: any = {
            success: args.success
        };
        output.writeStructBegin("GetPdp__Result");
        if (obj.success != null) {
            output.writeFieldBegin("success", thrift.TType.STRUCT, 0);
            PdpResponse.PdpResponseCodec.encode(obj.success, output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IGetPdp__Result {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 0:
                    if (fieldType === thrift.TType.STRUCT) {
                        const value_3: PdpResponse.IPdpResponse = PdpResponse.PdpResponseCodec.decode(input);
                        _args.success = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return {
            success: _args.success
        };
    }
};
export class GetPdp__Result extends thrift.StructLike implements IGetPdp__Result {
    public success?: PdpResponse.IPdpResponse;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IGetPdp__ResultArgs = {}) {
        super();
        if (args.success != null) {
            const value_4: PdpResponse.IPdpResponse = new PdpResponse.PdpResponse(args.success);
            this.success = value_4;
        }
    }
    public static read(input: thrift.TProtocol): GetPdp__Result {
        return new GetPdp__Result(GetPdp__ResultCodec.decode(input));
    }
    public static write(args: IGetPdp__ResultArgs, output: thrift.TProtocol): void {
        return GetPdp__ResultCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return GetPdp__ResultCodec.encode(this, output);
    }
}
export class Client<Context = any> extends thrift.ThriftClient<Context> {
    public static readonly serviceName: string = serviceName;
    public static readonly annotations: thrift.IThriftAnnotations = annotations;
    public static readonly methodAnnotations: thrift.IMethodAnnotations = methodAnnotations;
    public static readonly methodNames: Array<string> = methodNames;
    public readonly _serviceName: string = serviceName;
    public readonly _annotations: thrift.IThriftAnnotations = annotations;
    public readonly _methodAnnotations: thrift.IMethodAnnotations = methodAnnotations;
    public readonly _methodNames: Array<string> = methodNames;
    public readonly _methodParameters?: {
        [methodName: string]: number;
    } = methodParameters;
    public getPdp(request: PdpRequest.IPdpRequestArgs, context?: Context): Promise<PdpResponse.IPdpResponse> {
        const writer: thrift.TTransport = new this.transport();
        const output: thrift.TProtocol = new this.protocol(writer);
        output.writeMessageBegin("getPdp", thrift.MessageType.CALL, this.incrementRequestId());
        const args: IGetPdp__ArgsArgs = { request };
        GetPdp__ArgsCodec.encode(args, output);
        output.writeMessageEnd();
        return this.connection.send(writer.flush(), context).then((data: Buffer) => {
            const reader: thrift.TTransport = this.transport.receiver(data);
            const input: thrift.TProtocol = new this.protocol(reader);
            try {
                const { fieldName: fieldName, messageType: messageType }: thrift.IThriftMessage = input.readMessageBegin();
                if (fieldName === "getPdp") {
                    if (messageType === thrift.MessageType.EXCEPTION) {
                        const err: thrift.TApplicationException = thrift.TApplicationExceptionCodec.decode(input);
                        input.readMessageEnd();
                        return Promise.reject(err);
                    }
                    else {
                        const result: IGetPdp__Result = GetPdp__ResultCodec.decode(input);
                        input.readMessageEnd();
                        if (result.success != null) {
                            return Promise.resolve(result.success);
                        }
                        else {
                            return Promise.reject(new thrift.TApplicationException(thrift.TApplicationExceptionType.UNKNOWN, "getPdp failed: unknown result"));
                        }
                    }
                }
                else {
                    return Promise.reject(new thrift.TApplicationException(thrift.TApplicationExceptionType.WRONG_METHOD_NAME, "Received a response to an unknown RPC function: " + fieldName));
                }
            }
            catch (err) {
                return Promise.reject(err);
            }
        });
    }
}
export interface IHandler<Context = any> {
    getPdp(request: PdpRequest.IPdpRequest, context?: Context): PdpResponse.IPdpResponseArgs | Promise<PdpResponse.IPdpResponseArgs>;
}
export class Processor<Context = any> extends thrift.ThriftProcessor<Context, IHandler<Context>> {
    protected readonly _handler: IHandler<Context>;
    public static readonly serviceName: string = serviceName;
    public static readonly annotations: thrift.IThriftAnnotations = annotations;
    public static readonly methodAnnotations: thrift.IMethodAnnotations = methodAnnotations;
    public static readonly methodNames: Array<string> = methodNames;
    public readonly _serviceName: string = serviceName;
    public readonly _annotations: thrift.IThriftAnnotations = annotations;
    public readonly _methodAnnotations: thrift.IMethodAnnotations = methodAnnotations;
    public readonly _methodNames: Array<string> = methodNames;
    constructor(handler: IHandler<Context>) {
        super();
        this._handler = handler;
    }
    public process(input: thrift.TProtocol, output: thrift.TProtocol, context: Context): Promise<Buffer> {
        return new Promise<Buffer>((resolve, reject): void => {
            const metadata: thrift.IThriftMessage = input.readMessageBegin();
            const fieldName: string = metadata.fieldName;
            const requestId: number = metadata.requestId;
            const methodName: string = "process_" + fieldName;
            switch (methodName) {
                case "process_getPdp": {
                    resolve(this.process_getPdp(requestId, input, output, context));
                    break;
                }
                default: {
                    input.skip(thrift.TType.STRUCT);
                    input.readMessageEnd();
                    const errMessage = "Unknown function " + fieldName;
                    const err = new thrift.TApplicationException(thrift.TApplicationExceptionType.UNKNOWN_METHOD, errMessage);
                    output.writeMessageBegin(fieldName, thrift.MessageType.EXCEPTION, requestId);
                    thrift.TApplicationExceptionCodec.encode(err, output);
                    output.writeMessageEnd();
                    resolve(output.flush());
                    break;
                }
            }
        });
    }
    public process_getPdp(requestId: number, input: thrift.TProtocol, output: thrift.TProtocol, context: Context): Promise<Buffer> {
        return new Promise<PdpResponse.IPdpResponseArgs>((resolve, reject): void => {
            try {
                const args: IGetPdp__Args = GetPdp__ArgsCodec.decode(input);
                input.readMessageEnd();
                resolve(this._handler.getPdp(args.request, context));
            }
            catch (err) {
                reject(err);
            }
        }).then((data: PdpResponse.IPdpResponseArgs): Buffer => {
            const result: IGetPdp__ResultArgs = { success: data };
            output.writeMessageBegin("getPdp", thrift.MessageType.REPLY, requestId);
            GetPdp__ResultCodec.encode(result, output);
            output.writeMessageEnd();
            return output.flush();
        }).catch((err: Error): Buffer => {
            const result: thrift.TApplicationException = new thrift.TApplicationException(thrift.TApplicationExceptionType.UNKNOWN, err.message);
            output.writeMessageBegin("getPdp", thrift.MessageType.EXCEPTION, requestId);
            thrift.TApplicationExceptionCodec.encode(result, output);
            output.writeMessageEnd();
            return output.flush();
        });
    }
}
