/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface IPdpRequest {
    productId: number;
}
export interface IPdpRequestArgs {
    productId: number;
}
export const PdpRequestCodec: thrift.IStructCodec<IPdpRequestArgs, IPdpRequest> = {
    encode(args: IPdpRequestArgs, output: thrift.TProtocol): void {
        const obj: any = {
            productId: args.productId
        };
        output.writeStructBegin("PdpRequest");
        if (obj.productId != null) {
            output.writeFieldBegin("productId", thrift.TType.I32, 1);
            output.writeI32(obj.productId);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[productId] is unset!");
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IPdpRequest {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.I32) {
                        const value_1: number = input.readI32();
                        _args.productId = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.productId !== undefined) {
            return {
                productId: _args.productId
            };
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read PdpRequest from input");
        }
    }
};
export class PdpRequest extends thrift.StructLike implements IPdpRequest {
    public productId: number;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IPdpRequestArgs) {
        super();
        if (args.productId != null) {
            const value_2: number = args.productId;
            this.productId = value_2;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[productId] is unset!");
        }
    }
    public static read(input: thrift.TProtocol): PdpRequest {
        return new PdpRequest(PdpRequestCodec.decode(input));
    }
    public static write(args: IPdpRequestArgs, output: thrift.TProtocol): void {
        return PdpRequestCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return PdpRequestCodec.encode(this, output);
    }
}
