/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface IPdpResponse {
    id?: number;
    name?: string;
    price?: number;
}
export interface IPdpResponseArgs {
    id?: number;
    name?: string;
    price?: number;
}
export const PdpResponseCodec: thrift.IStructCodec<IPdpResponseArgs, IPdpResponse> = {
    encode(args: IPdpResponseArgs, output: thrift.TProtocol): void {
        const obj: any = {
            id: args.id,
            name: args.name,
            price: args.price
        };
        output.writeStructBegin("PdpResponse");
        if (obj.id != null) {
            output.writeFieldBegin("id", thrift.TType.I32, 1);
            output.writeI32(obj.id);
            output.writeFieldEnd();
        }
        if (obj.name != null) {
            output.writeFieldBegin("name", thrift.TType.STRING, 2);
            output.writeString(obj.name);
            output.writeFieldEnd();
        }
        if (obj.price != null) {
            output.writeFieldBegin("price", thrift.TType.I32, 3);
            output.writeI32(obj.price);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IPdpResponse {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.I32) {
                        const value_1: number = input.readI32();
                        _args.id = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.STRING) {
                        const value_2: string = input.readString();
                        _args.name = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.TType.I32) {
                        const value_3: number = input.readI32();
                        _args.price = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return {
            id: _args.id,
            name: _args.name,
            price: _args.price
        };
    }
};
export class PdpResponse extends thrift.StructLike implements IPdpResponse {
    public id?: number;
    public name?: string;
    public price?: number;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IPdpResponseArgs = {}) {
        super();
        if (args.id != null) {
            const value_4: number = args.id;
            this.id = value_4;
        }
        if (args.name != null) {
            const value_5: string = args.name;
            this.name = value_5;
        }
        if (args.price != null) {
            const value_6: number = args.price;
            this.price = value_6;
        }
    }
    public static read(input: thrift.TProtocol): PdpResponse {
        return new PdpResponse(PdpResponseCodec.decode(input));
    }
    public static write(args: IPdpResponseArgs, output: thrift.TProtocol): void {
        return PdpResponseCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return PdpResponseCodec.encode(this, output);
    }
}
