/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface ISectionDetail {
    sectionId?: string;
    border?: string;
}
export interface ISectionDetailArgs {
    sectionId?: string;
    border?: string;
}
export const SectionDetailCodec: thrift.IStructCodec<ISectionDetailArgs, ISectionDetail> = {
    encode(args: ISectionDetailArgs, output: thrift.TProtocol): void {
        const obj: any = {
            sectionId: args.sectionId,
            border: args.border
        };
        output.writeStructBegin("SectionDetail");
        if (obj.sectionId != null) {
            output.writeFieldBegin("sectionId", thrift.TType.STRING, 1);
            output.writeString(obj.sectionId);
            output.writeFieldEnd();
        }
        if (obj.border != null) {
            output.writeFieldBegin("border", thrift.TType.STRING, 2);
            output.writeString(obj.border);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): ISectionDetail {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_1: string = input.readString();
                        _args.sectionId = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.STRING) {
                        const value_2: string = input.readString();
                        _args.border = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return {
            sectionId: _args.sectionId,
            border: _args.border
        };
    }
};
export class SectionDetail extends thrift.StructLike implements ISectionDetail {
    public sectionId?: string;
    public border?: string;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: ISectionDetailArgs = {}) {
        super();
        if (args.sectionId != null) {
            const value_3: string = args.sectionId;
            this.sectionId = value_3;
        }
        if (args.border != null) {
            const value_4: string = args.border;
            this.border = value_4;
        }
    }
    public static read(input: thrift.TProtocol): SectionDetail {
        return new SectionDetail(SectionDetailCodec.decode(input));
    }
    public static write(args: ISectionDetailArgs, output: thrift.TProtocol): void {
        return SectionDetailCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return SectionDetailCodec.encode(this, output);
    }
}
